### ISSUE TITLE
multi-processing issue while running on Google Colab

### ISSUE THREAD

**Issue by binod132** [keplerlab/katna#1]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-93c3d7344eb8> in <module>()
      4 
      5 #instantiate the video class
----> 6 vd = Video()
      7 
      8 #number of key-frame images to be extracted

2 frames
/usr/lib/python3.6/multiprocessing/pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    165             processes = os.cpu_count() or 1
    166         if processes < 1:
--> 167             raise ValueError("Number of processes must be at least 1")
    168 
    169         if initializer is not None and not callable(initializer):

ValueError: Number of processes must be at least 1

**Comment by ermac2694** [comment]
@binod132 The issue has been resolved.
