### ISSUE TITLE
ValueError: Input vector needs to be bigger than window size.

### ISSUE THREAD

**Issue by johnbager** [keplerlab/katna#10]
I have found new erro.  I use
 imgs = vd.extract_video_keyframes(no_of_frames = no_of_frames_to_return, file_path= video_file_path)
  to extract keyframe frome my video.

https://user-images.githubusercontent.com/38372764/110414586-155c0280-80cb-11eb-8006-1906aeef842e.mp4

**Comment by mayank10j** [comment]
Able to replicate the issue with given video, will update when fixed.

**Comment by mayank10j** [comment]
version 0.8.2 fixes your issue, Please reinstall and try again.
