### ISSUE TITLE
Facing out of memory error

### ISSUE THREAD

**Issue by suprateek-sc19** [keplerlab/katna#12]
Memory not getting cleared and python crashing when running script on >30 videos

**Comment by thealokkr** [comment]
Could you share following details
1. OS
2. RAM
3. Max Video size
4. And the video function you used

**Comment by suprateek-sc19** [comment]
Sure
1. Windows 10
2. 24 gb ram
3. Max video size was around 65 mb
4. vd.extract_video_keyframes

**Comment by thealokkr** [comment]
And what is the python version you are using?
Can you try with python 3.8 or 3.9?

**Comment by mayank10j** [comment]
This memory leak issue is fixed in katna version 0.9.0, kindly test and confirm.

**Comment by suprateek-sc19** [comment]
Getting this error now

All the files in directory directory_name/video_name.mp4 are invalid video files

**Comment by thealokkr** [comment]
@suprateek-sc19 There are breaking changes from the last version. You may want to check the documentation

**Comment by suprateek-sc19** [comment]
Yep, my bad. It is working and the memory leak issue has been fixed. Thanks!
