### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by zongzi3zz** [keplerlab/katna#16]
We Call the **extract_video_keyframes** method to extract the keyframes of the following video , but the following problem occurs:
![46171619244244_ pic_hd](https://user-images.githubusercontent.com/48664486/115949321-eed11a00-a506-11eb-8c30-3ed821b8d222.jpg)

https://user-images.githubusercontent.com/48664486/115949386-6dc65280-a507-11eb-89ef-fcfd73ac0e2b.mp4

**Comment by mayank10j** [comment]
Can you please mention your operating system, OS Version, Python version ?
I am able to run on your given video without issue on my system.

**Comment by zongzi3zz** [comment]
My OS Version is Ubuntu 16.04 and Python version is 3.6.10. And just a few videos have the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keplerlab/katna"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 下午2:45
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [keplerlab/katna] Conversion failed (#16)





 
Can you please mention your operating system, OS Version, Python version ?
 I am able to run on your given video without issue on my system.

**Comment by mayank10j** [comment]
Not able to replicate issue on Ubuntu 16.04 with Python version 3.6.10 with your given video and other videos. 
Can you please any video with issue.

**Comment by zongzi3zz** [comment]
I solved it by reinstalling Katna.Thank you for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keplerlab/katna"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 晚上8:04
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [keplerlab/katna] Conversion failed (#16)





 
Not able to replicate issue on Ubuntu 16.04 with Python version 3.6.10 with your given video and other videos.
 Can you please any video with issue.
