### ISSUE TITLE
About extract_video_keyframes only return 4 frames

### ISSUE THREAD

**Issue by jiaka** [keplerlab/katna#17]
when I call the extract_video_keyframes method
No matter what The parameter 'no_of_frames' set to, 
only 4 frames of images will be returned

this is my code

```
from Katna.video import Video
from Katna.writer import KeyFrameDiskWriter

vd = Video()

diskwriter = KeyFrameDiskWriter(location="selectedframes")

video_file_path = 'D:/video/color.avi'
no_of_frames_to_returned = 40

frame = vd.extract_video_keyframes(
     no_of_frames=no_of_frames_to_returned, file_path=video_file_path,
     writer=diskwriter
)

```
my video have 171 frames and no_of_frames is equal to 40, but only return four frames.

please help me ,please

**Comment by jiaka** [comment]
Why can't I find the k-means method to extract the key frame, and I can't set thresholds and select the five 'extract key frame' methods casually.

**Comment by thealokkr** [comment]
Hi, Can you try with some other video? No. of frames to be returned  is not hardcoded.  This may happen if the library is only able to extract 4 eligible frames
