### ISSUE TITLE
sorting of the output key frame images

### ISSUE THREAD

**Issue by HuitMahoon** [keplerlab/katna#19]
The sorting of the output key frame images is random, not the order of video frames. It is highly recommended that the name of the output image is the frame ID.

**Comment by nitinkatyal1314** [comment]
> The sorting of the output key frame images is random, not the order of video frames. It is highly recommended that the name of the output image is the frame ID.

Share the sample code and the input file you are using so we can replicate this issue.

**Comment by HuitMahoon** [comment]
```
video_file_path = os.path.join(".", "tests", "data", "Tidead.mp4")  
vd = Video()

no_of_frames_to_returned = 10

diskwriter = KeyFrameDiskWriter(location="selectedframes")

vd.extract_video_keyframes(

    no_of_frames=no_of_frames_to_returned, file_path=video_file_path,

    writer=diskwriter

)
```

The extracted key frames were  saved in folder "selectedframes" , but the sorting is random and the name of the output image file is not the ID in the sequeces.
So how to rename the output image file with its exact location in the sequences?Thanks.
@nitinkatyal1314

**Comment by HuitMahoon** [comment]
@nitinkatyal1314  
Inside the image_selector.py class, I have sorted the return values, so:
`return sorted(variance_laplacians)` and` return sorted(filtered_items)`The output images are in sequence.

But I am still confused, the name of the output always just start from 0 to N, not the exact frame ID in the sequence.
In some scenarios, we may want to know the exact **location** of the output. Could you please give me some tips about how to solve it?It may need significant code changes.

**Comment by HuitMahoon** [comment]
@nitinkatyal1314  
I am trying to make some code modifications to solve this. Just return the index LIST along with frame LIST.

**Comment by HuitMahoon** [comment]
Finally, by making some code changes, I successfully fulfill this function which is  to rename the output image file with its exact location in the sequences.

**Comment by appledora** [comment]
@HuitMahoon could you kindly share your code here?

**Comment by thealokkr** [comment]
@HuitMahoon closing the issue.

**Comment by LilyDaytoy** [comment]
> Finally, by making some code changes, I successfully fulfill this function which is to rename the output image file with its exact location in the sequences.

I also encounted this question, could you kindly share your codes here ;D

**Comment by ooguzzzz** [comment]
> Son olarak, bazı kod değişiklikleri yaparak, çıktı görüntü dosyasını dizilerdeki tam konumu ile yeniden adlandırmak olan bu işlevi başarıyla yerine getiriyorum.
I'm stuck on this, I can't progress, can you share the code?

**Comment by oztrkoguz** [comment]
> Finally, by making some code changes, I successfully fulfill this function which is to rename the output image file with its exact location in the sequences.

I'm stuck on this, I can't progress, can you share the code?

**Comment by HuitMahoon** [comment]
> Inside the image_selector.py class, I have sorted the return values, so:
> `return sorted(variance_laplacians)` and` return sorted(filtered_items)`The output images are in sequence.

Inside the image_selector.py class, the return list can be sorted from ) to N, so:
return sorted(variance_laplacians) and return sorted(filtered_items)The output images are in sequence.
Inside the frame_extractor.py , in funciton __process_frame() , just add a LIST of `frameIndexes `along with `frames `or `frame_diffs`, and make some corresponding changes to return these indexes.

The source code is not available on my other pc. It is not that complicated ,so  you may try on your own. ;D
