### ISSUE TITLE
Image Sorting

### ISSUE THREAD

**Issue by saurabh986** [keplerlab/katna#2]
Can you please help me for sorting the extracted images from video. The extracted Images are not in sequence as per video playback.

**Comment by saurabh986** [comment]
> Can you please help me for sorting the extracted images from video. The extracted Images are not in sequence as per video playback.

Finally got sorted result by Modifying the `image_selector.py` class
Here I applied `sorted(variance_laplacians)` & `sorted(filtered_items)` which gave me results images in sequence.

**Comment by HuitMahoon** [comment]
> > Can you please help me for sorting the extracted images from video. The extracted Images are not in sequence as per video playback.
> 
> Finally got sorted result by Modifying the `image_selector.py` class
> Here I applied `sorted(variance_laplacians)` & `sorted(filtered_items)` which gave me results images in sequence.

after modifided iamge_selector.py class as you suggest, it doesn't seem  to work. Could you give more detailed code change?

**Comment by basakozsoy** [comment]
@HuitMahoon, inside the `image_selector.py` class, I have sorted the return values, so: 
`return sorted(variance_laplacians)` and `return sorted(filtered_items)`
The output images are in sequence.

**Comment by HuitMahoon** [comment]
@basakozsoy , After modified the `return sorted(variance_laplacians) `and` return sorted(filtered_items)`, should I run "python setup.py install" to reinstall katna module?

**Comment by basakozsoy** [comment]
@HuitMahoon No, simply saving the changes on image_selector.py is enough. You can run your own code afterwards.

**Comment by HuitMahoon** [comment]
@basakozsoy , Thanks a lot, it finally works for me. The output images are in sequence.
But I am still confused, the name of the output always just start from 0 to N, not the exact frame ID in the sequence.
In some scenarios, we may want to know the exact location of the output. Could you give me some tips about how to solve it?

To this end, maybe we need to convert the `variance_laplacians` and `filtered_items` type to **dict**, and make some significant corresponding code changes

**Comment by HuitMahoon** [comment]
Finally, by making some code changes, I successfully fulfill this function which is  to rename the output image file with its exact location in the sequences.
