### ISSUE TITLE
key frames extraction: any references?

### ISSUE THREAD

**Issue by zjmwqx** [keplerlab/katna#21]
it seems the "key frames extraction methods" works well, is there any referring papers I can get more detail info from?

**Comment by thealokkr** [comment]
You may want to read SAD (Sum of absolute difference)

**Comment by zjmwqx** [comment]
> You may want to read SAD (Sum of absolute difference)


Here is your wiki script :
" Frame extraction and selection criteria for key-frame extraction

Frame that are sufficiently different from previous ones using absolute differences in LUV color-space
Brightness score filtering of extracted frames
Entropy/contrast score filtering of extracted frames
K-Means Clustering of frames using image histogram
Selection of best frame from clusters based on and variance of Laplacian (image blur detection)"


I think "Frame that are sufficiently different from previous ones" is the most important step to follow. But I don't understand why it can generate good key frames. And why the following cluster process and blur detection should be added? Is there any paper to refer?

**Comment by thealokkr** [comment]
Closing the question as it is not an issue
