### ISSUE TITLE
Why do I have to set no_of_frames? 

### ISSUE THREAD

**Issue by jaycecd** [keplerlab/katna#23]
1. Why do I have to set _no_of_frames_? 
2. What is the maximum value of _no_of_frames_?
3. Can the algorithm automatically find out images that are different from other frames as keyframes without setting _no_of_frames_? 
4. If I set _no_of_frames_ to a very large number, does it mean that every frame will be extracted?
Thank you for your reply!

**Comment by thealokkr** [comment]
1. Most of the use cases required us to return representative frames and not all the different frames
2. There is no maximum value. If you requested 100 frames and the library was able to find only 6 then it will return 6 only
3. Not in the current implementation, you may want to try a high number. Do note that large video with large no. of frames may cause performance issue.
4. Some filtration would still be done but you can try setting up a higher value

**Comment by jaycecd** [comment]
Thank you very much for your reply, which answered my question in detail, but it triggered a new question. As you said, how much should _no_of_frames_ be set for a large video (such as 1 hour)? What is the relationship between video duration and _no_of_frames_  (such as function expression)?

**Comment by thealokkr** [comment]
1. A longer video with a lot of moving/changing frames will generate a lot of frames.
2. It is not just about the length but the resolution as well. Higher the resolution would require bigger matrix to be stored. 
3. Long video under the hood is split into short clips to handle long videos
4. If you need all the frames of the video, then katna would be an overkill. Vanilla openCV would be a better option
5. You can try with 50-60 key frames from you 30-40 min. long video 
6.

**Comment by jaycecd** [comment]
Thank you very much for your answer, which helped me a lot.
