### ISSUE TITLE
'Video' object has no attribute 'extract_frames_as_images'

### ISSUE THREAD

**Issue by Ojasvi-97** [keplerlab/katna#25]
The specified method isn't working.

**Comment by thealokkr** [comment]
Did you try running the sample app?

**Comment by Ojasvi-97** [comment]
I did, it still gives me the same error.

**Comment by thealokkr** [comment]
Are you installing from PIP or directly from source?

**Comment by thealokkr** [comment]
Closing the issue in absence of further details

**Comment by neslihanedes** [comment]
Hi!

I'm having the same issue. I've installed it via pip. Any suggestions?
