### ISSUE TITLE
after vd.extract_frames_as_images，can i locating which frame positon of the result

### ISSUE THREAD

**Issue by datalee** [keplerlab/katna#4]
after i extract the key frames ,can i locating which frame positon of the result?
thks

**Comment by mayank10j** [comment]
This functionality is not available in katna as of yet. This seems to be doable but needs to be developed separately.

**Comment by haitian2du** [comment]
> 提取关键帧后，我能否定位结果的哪个帧位置？
> thks

Hello, I have the same needs, have you solved this problem? Welcome to contact me: 1340398672@qq.com
