### ISSUE TITLE
image co ordinates

### ISSUE THREAD

**Issue by krishnakatyal** [keplerlab/katna#7]
i want to know how i can extract the corinates of the smart cropped image  in respect to the original image like
crop{
x:
y:
weigth:
height:}

**Comment by mayank10j** [comment]
All of Katna image smart cropping functions like crop_image_from_cvimage, crop_image_with_aspect and crop_image etc. returns list of crop rectangle,
You can iterate this list of crop rectangles and get x,y, w,h parameters from them, for details check out this reference:
https://katna.readthedocs.io/en/latest/Katna.html#module-Katna.crop_rect
or source file for https://katna.readthedocs.io/en/latest/_modules/Katna/crop_rect.html#CropRect
