### ISSUE TITLE
How to output specified image size only?

### ISSUE THREAD

**Issue by nerdyrodent** [keplerlab/katna#8]
Using the example "crop all images in a single directory", if I use:
```
# crop dimensions
crop_width = 512
crop_height = 512
```
Then I'll also get images that are 460x460, as well as 512x512. Is there a way to force the specified dimensions only?

**Comment by mayank10j** [comment]
This seems to be a bug, I will test it out at my end and revert with fix, 
It would also be helpful if, If you can also post some of the images where you are getting 460x460 crops.

**Comment by nerdyrodent** [comment]
For this example image, the first crop was 1024x1024, the other 3 were 921x913.
![Cat1](https://user-images.githubusercontent.com/74688049/109924902-e7388600-7cb8-11eb-92eb-e79a423ffa56.jpg)
Example:
![Cat1_cropped_1](https://user-images.githubusercontent.com/74688049/109925107-38e11080-7cb9-11eb-8ec9-2fc4c1e3de6c.jpeg)

**Comment by mayank10j** [comment]
Fixed bug where incorrect specification crops were returned in crop_image and crop_image_with_dir method with updated release v0.7.1 for katna, Please reinstall Katna and update.
