### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by johnbager** [keplerlab/katna#9]
when i use kanta to process my video , it send this erro.could you tell me how to solve it?

https://user-images.githubusercontent.com/38372764/110197043-bf494e00-7e83-11eb-982d-5ddb8dc9bbcc.mp4

**Comment by johnbager** [comment]
i used:
imgs = vd.extract_video_keyframes(no_of_frames = no_of_frames_to_return, \
file_path= video_file_path)


i aimed to extract keyframe

**Comment by thealokkr** [comment]
Thank you for the data. We are able to replicate the issue.

**Comment by johnbager** [comment]
it's trouble for you. If you can solve it ,please tell me. Thanks.

**Comment by thealokkr** [comment]
There seems to be an issue with the video encoding. You can fix the video by using handbrake https://handbrake.fr/. We are looking at exception handling in code separately

**Comment by mayank10j** [comment]
Issue is fixed in new release v0.8.1, Please reinstall Katna for updated version.
